### ISSUE TITLE
Example for parameterized routes

### ISSUE THREAD

**Issue by Wirone** [vlaja/multilanguage-routing-react#9]
I've just read [your post](https://medium.com/prototyped/multi-language-routing-in-react-d7eb7a0688e9) (thanks!) and I'm wondering if your approach supports parameters in localized paths. If so, how to achieve it?

Example in this demo app would be great.

**Comment by vlaja** [comment]
Hey man.

Can you give me an example of what exactly you need in order to avoid any confusion. Are we talking about query params?

If this is the case, it wasn't the intention of the initial example, but it can be supported. I do plan on creating a react package around this, to account for such requirements.

**Comment by Wirone** [comment]
@vlaja I'm talking about route params. In your demo there are only simple routes, I would like to know if it's possible to handle translation like this:

- EN: `/book/:id/reviews`
- DE: `/de/buch/:id/bewertungen`

where `:id` is not translatable, is the same for all languages.

**Comment by DimitriDaSilva** [comment]
Agreed. Handling route params would make this great approach viable for more complex projects.

Has anyone found a way to implement it here?

**Comment by vlaja** [comment]
Hi @Wirone @DimitriDaSilva sorry, as this was an article support repository I have set it aside for a while due to other obligations.

I should have some time in the near future to try to address this, and probably convert this into a library.

Feel free to leave your comments or suggestions about the requirements you want to support, so I can get a better feel of how to make this more flexible.

Also, appreciate the comments.

**Comment by DimitriDaSilva** [comment]
Thanks @vlaja! 2 years have passed since your article and internationalization still seems to be a pain to implement. So thanks for the article and the example, it definitely helps.

Okay, I'll try to implement route params based on what you did and I'll give you a feedback!

**Comment by Wirone** [comment]
@vlaja any news on this 😅?

**Comment by vlaja** [comment]
@Wirone Unfortunately not :(

I am pinning this issue and will try to help you out with this. I really appreciate you still finding this relevant and do apologize for simply not finding time to tackle this.

In the meantime, I've mostly moved to using next.js for my private projects, and also inside our company, and they do actually have plugins that do address this in combination with next.js/@reach-router, which might be worth looking into from your side as well.

**Comment by Wirone** [comment]
Not a problem @vlaja 🙂 I was just clearing my list of issues/PRs yesterday, this is not urgent for me since I don't work with frontend currently. But may be worth to do it anyway 🙂

**Comment by Wirone** [comment]
Don't need it anymore and since I don't want it on "my issues" list, I'm going to close it now.

Anyone interested in this: please file new issue and reference this one.
